### ISSUE TITLE
Duplicated "his" occurs in "Cinderella"

### ISSUE THREAD

**Issue by jpnance** [standardebooks/jacob-grimm_wilhelm-grimm_household-tales_margaret-hunt#1]
https://github.com/standardebooks/jacob-grimm_wilhelm-grimm_household-tales_margaret-hunt/blob/f4a94876d45fa52626deb18f758ac084017fca33/src/epub/text/cinderella.xhtml#L67

"Then he took her on his his horse..."

It looks like this error is also in the original Project Gutenberg text so I'll submit that errata to them separately.

**Comment by acabal** [comment]
Thanks, this should be fixed now!
